name: Suffix
version: '${projectVersion}'
main: net.okocraft.suffix.bukkit.Main
description: Plugin that implements suffix command.
depend: [ "LuckPerms" ]
api-version: "1.13"

commands:
  suffix:
    description: "Command that changes suffix of player."
    permission: "suffix.use"

permissions:
  suffix.use:
    default: op
  suffix.other:
    default: op
  suffix.unlimited.length:
    default: op
  suffix.unlimited.pattern:
    default: op