messages:
  specify-player: "&7* プレイヤーを指定してください。"
  specify-suffix: "&7* suffixを指定してください。"
  player-not-found: "&7* プレイヤーが見つかりませんでした。"
  player-only: "&7* プレイヤーにしか実行できません。"
  too-long-suffix: "&7* suffixが長すぎます。%length% 文字以下にしてください。"
  blacklist-pattern: "&7* %pattern% を含むsuffixは設定できません。"

suffix-length: 1 # except color codes.
blacklist-pattern: []

suffix-apply-command: "lp user %player_name% meta setsuffix 10 %suffix%"