name: Build
on: [ push, pull_request ]

jobs:
  build-java-11:
    uses: okocraft/workflows/.github/workflows/gradle.yml@v1
    with:
      java-version: '11'
      package-name: Suffix-Build-${{ github.run_number }}
  build-java-17:
    uses: okocraft/workflows/.github/workflows/gradle.yml@v1
    with:
      java-version: '17'
      package-name: Suffix-Build-${{ github.run_number }}
